### ISSUE TITLE
Invalid character F looking for beginning of value.

### ISSUE THREAD

**Issue by dbd** [camelpac/alpaca-proxy-agent#1]
When trying to connect via rest to bars after registering for a stream I receive the following error in go.

```
go run main.go
panic: invalid character 'F' looking for beginning of value

goroutine 1 [running]:
main.main()
        /main.go:33 +0x391
exit status 2
```

```
docker run -it -p 8765:8765 shlomik/alpaca-proxy-agent



   _   _                           ___
  /_\ | |_ __   __ _  ___ __ _    / _ \_ __ _____  ___   _
 //_\\| | '_ \ / _` |/ __/ _` |  / /_)/ '__/ _ \ \/ / | | |
/  _  \ | |_) | (_| | (_| (_| | / ___/| | | (_) >  <| |_| |
\_/ \_/_| .__/ \__,_|\___\__,_| \/    |_|  \___/_/\_\\__, |
        |_|                                          |___/

                   _                    _
                  /_\   __ _  ___ _ __ | |_
                 //_\\ / _` |/ _ \ '_ \| __|
                /  _  \ (_| |  __/ | | | |_
                \_/ \_/\__, |\___|_| |_|\__|
                       |___/



2020-10-01 19:08:54,968 root Alpaca Proxy Agent v0.5.5
2020-10-01 19:08:54,968 root Using the Alpaca Websocket
< {'action': 'authenticate', 'data': {'key_id': '...', 'secret_key': '...'}}
< {'action': 'listen', 'data': {'streams': ['Q.AAPL']}}
code = 1006 (connection closed abnormally [internal]), no reason
Done
2020-10-01 19:08:58,696 root connected to: wss://data.alpaca.markets/stream
```

Here is an [example](https://gist.github.com/dbd/747a23ef9fea9c887dafc9aa7a2a1323) to test with.

**Comment by shlomiku** [comment]
Hi!
you've opened the first issue of this project - exciting :)

I'm not sure I understand, you are saying that you are having issues with the REST api?

Alpaca provides 2 services:
* rest
* websocket stream

this project only changes the websocket stream. the REST calls are going directly to the alapca servers, not going through the docker container.

**Comment by shlomiku** [comment]
I have executed your code example and got this:
![image](https://user-images.githubusercontent.com/7924802/94896390-062ab600-0496-11eb-866f-fbe7c662634b.png)


but your code example didn't use the streaming service at all.

**Comment by dbd** [comment]
Thanks for the quick response!

I may have misunderstood the project, at the moment it doesn't seem like it is possible to use a proxy for the stream and use the default dataUrl for the rest queries in the go SDK. So by setting the `APCA_DATA_URL` you are changing the URL for both.

As for the code example, I must have had a dirty environment, manually exporting `APCA_DATA_URL` will make it the local proxy.
The code example should run continuously now and print the quotes and trade updates as they are streamed.

**Comment by shlomiku** [comment]
It's a bit weird because the python sdk is using the "https://paper-api.alpaca.markets" url
I will try to separate the url usage in the go sdk and check it out tomorrow once the market opens

**Comment by dbd** [comment]
That is what I ended up doing as well and then just running my own fork for the time being. I made a [PR ](https://github.com/alpacahq/alpaca-trade-api-go/pull/93) if you can review it. 

Feel free to close this as this is a SDK issue.

**Comment by shlomiku** [comment]
sure. let's move the conversation there.
