### ISSUE TITLE
How to connect

### ISSUE THREAD

**Issue by yiftachn** [camelpac/alpaca-proxy-agent#3]
Sorry for the lame question, but I'm inexperienced with websockets and networking.
After the docker is up and running, how do I make my client connect to the server? what is the format of the json to pass to it? Do I need to reference the sdk base url to the proxy-agent url?

**Comment by shlomiku** [comment]
Hi,
take a look at these posts for more details:
https://alpaca.markets/learn/alpaca-proxy-agent-01/
https://alpaca.markets/learn/alpaca-proxy-agent-02/
