### ISSUE TITLE
Raspberry pi throws error when attempting to execute proxy agent

### ISSUE THREAD

**Issue by dallinlarsen** [camelpac/alpaca-proxy-agent#4]
When I try to execute the docker image on my raspberry pi I get the following error:
`standard_init_linux.go:211: exec user process caused "exec format error"`

A couple places online says this happens with docker when the image isn't compatible with the ARM architecture of the processor. I'm not completely sure this is the issue because I am not very familiar with docker. I ran the image on my PC and it worked perfect but my PC has a x64 architecture.

Does anyone know what I could do to resolve this error?

**Comment by shlomiku** [comment]
Hi, this image is using this base python image: `FROM python:3.6-slim`. try checking if there's a different image for python on raspberry and change the dockerfile.

**Comment by shlomiku** [comment]
do update here if you get it working :)

**Comment by dallinlarsen** [comment]
Sorry I didn't post back earlier but a little bit ago I did some digging into docker and found the solution. The python image that docker was using in the project was a build for x64 processors. I did as @shlomikushchi suggested and used a different image for python and rebuilt the docker image with the following as the Dockerfile:

```
FROM arm64v8/python:3.6-slim

RUN pip install alpaca-trade-api==0.50.1 \
                websockets==8.1

RUN apt-get install ca-certificates

WORKDIR /opt/project

COPY . /opt/project/

CMD python main.py

# Set some environment variables.
# PYTHONUNBUFFERED keeps Python from buffering our standard output stream,
# which means that logs can be delivered to the user quickly.
# PYTHONDONTWRITEBYTECODE keeps Python from writing the .pyc files which are
# unnecessary in this case. We also update

ENV PYTHONUNBUFFERED=TRUE
ENV PYTHONDONTWRITEBYTECODE=TRUE
```

Notice that it isn't just `FROM python:3.6-slim` it is `FROM arm64v8/python:3.6-slim` on the first line. This is what needed to be changed.

**Comment by shlomiku** [comment]
nice!
